dynamic11/wet-react

.eslintrc.json, __mocks__/react-syntax-highlighter.tsx, jest.config.js, jest.setup.ts, package-lock.json, package.json, src/components/CodeBlock/CodeBlock.test.tsx, src/components/CodeBlock/CodeBlock.tsx, src/components/CodeBlock/index.ts, src/components/CodeBlock/stories/CodeBlock.intro.stories.mdx, src/components/CodeBlock/stories/CodeBlock.languages.stories.mdx, src/components/CodeBlock/stories/CodeBlock.linenumber.stories.mdx, src/components/index.ts, tsconfig.json
- add CodeBlock component
- Create jest mock for react-syntax-highlighter so tests don't fail due to a type error (needs to be investigated)
- documented component in storybook
=> [New] implement CodeBlock component

.storybook/preview.js, .vscode/settings.json, package-lock.json, package.json
Sorts the stories to be have introductions first
=> [New] Story sort to have "Intro" first

src/components/Alert/stories/Alert.intro.stories.mdx, src/components/Panel/Panel.tsx, src/components/Panel/index.ts, src/components/Panel/stories/Panel.footer.stories.mdx, src/components/Panel/stories/Panel.header.stories.mdx, src/components/Panel/stories/Panel.intro.stories.mdx, src/components/Panel/stories/Panel.variants.stories.mdx, src/components/index.ts
🌟  New Feature:
- Implement the Panel component form WET: [WET Documentation](https://wet-boew.github.io/wet-boew-styleguide/design/panels-en.html)
- added storybook stories for all prop usages
⚠️ Component tests needs to be implemented
=> [New] implement Panel component

.github/workflows/ci-tests.yaml, .gitignore, jest.config.js, package.json
⭐  New feature
- add code coverage support for jest
- set coverage thresholds
- upload results to codecov
=> [New] Add code coverage checks

jest.config.js, src/components/Alert/Alert.test.tsx, src/components/Alert/Alert.tsx, src/components/Panel/Panel.test.tsx, src/components/Panel/Panel.tsx
⭐  New Features:
- add tests for Alert component
- update code coverage
=> [New] Add tests for Alert component

jest.config.js, src/components/Link/Link.test.tsx, src/components/Link/Link.tsx
⭐  New Feature:
- implement test for Link component
- update code coverage
=> [New] implement tests for Links

src/components/ButtonGroup/ButtonGroup.test.tsx, src/components/ButtonGroup/ButtonGroup.tsx
⭐  New Features:
- added more extensive (better quality) testing
- code coverage unchanged
=> [New] Implement tests for ButtonGroup component

jest.config.js, src/components/Label/Label.test.tsx, src/components/Label/Label.tsx
⭐  New Features:
- made Label tests more thorough 
- code coverage unchanged
=> [Fix] Improve Label tests

.eslintignore, .eslintrc.json, .github/workflows/npm-publish.yaml, .prettierignore, package-lock.json, package.json, rollup.config.js, tsconfig.json
⭐  **New Features:**
- build package with rollup
- implement workflow to deploy package to npm.js
=> [New] Build and publish app to NPM.js

src/components/Alert/Alert.test.tsx, src/components/Badge/Badge.test.tsx, src/components/ButtonGroup/ButtonGroup.test.tsx, src/components/Label/Label.test.tsx, src/components/Link/Link.test.tsx, src/components/Panel/Panel.test.tsx, src/components/ProgressBar/ProgressBar.test.tsx
- update variable names in test files for consistency
=> [Fix] Update variable names for tests

src/components/Badge/stories/Badge.intro.stories.mdx, src/components/Button/stories/Button.intro.stories.mdx, src/components/CodeBlock/stories/CodeBlock.intro.stories.mdx, src/components/Label/stories/Label.intro.stories.mdx, src/components/Link/stories/Link.intro.stories.mdx, src/components/Text/stories/Text.intro.stories.mdx, src/components/Title/stories/Title.intro.stories.mdx
⭐ **New Feature**
- move Intro example into a canvas component for consistency and easy reference
=> [New] Move Intro example into a canvas component

jest.config.js, src/components/Title/Title.tsx
- Simplify Tag selection logic for different heading levels
=> [Fix] Simplify logic for Heading 

jest.config.js, src/components/Text/Text.test.tsx, src/components/Text/stories/Text.background.stories.mdx
- implement tests for Text
- update code coverage
- remove unused story
no screen shots
=> [New] Implement tests for Text component

jest.config.js, src/components/Title/Title.test.tsx
- improve tests for tile
- update code coverage
no screenshots
=> [Fix] improve tests for Title

README.md
Reformatted README since it was causing issues with Prettier during CI
=> [Fix] Reformatted README for Prettier

src/components/Form/FormCheck.tsx, src/components/Form/index.ts, src/components/Form/stories/Form.check.stories.mdx, src/components/Form/stories/Form.control.stories.mdx, src/components/Form/stories/Form.intro.stories.mdx, src/components/Form/stories/Form.label.stories.mdx, src/components/Form/stories/Form.select.stories.mdx, src/components/Form/stories/Form.text.stories.mdx, src/style.css
- implement 'checkbox' and 'radio' for forms
=> [New] Implement 'checkbox' and 'radio' for forms

README.md, src/stories/welcome.stories.mdx
- Add installation section to README
- It explains how to install the components and apply stylesheets
- Update storybook intro to include the instructions
=> [New] Add installation instruction to README

.github/workflows/ci-tests.yaml
- Update CI/CD Job name ('build' ---> 'test')
no screenshots
=> [Fix] Update CI/CD Job name

.github/pull_request_template.md
- add issue reference to PR template
=> [New] Add issue reference to PR template

README.md
- Fix GitHub actions link in README tag
no screenshots
=> [Fix] GitHub actions link in README tag

rollup.config.js, src/components/Form/FormControl.tsx, src/components/Form/FormSelect.tsx
- define types for the `onChange` prop in `FormControl`, and `FormSelect`
no screenshots
=> [Fix] Resolve errors/warnings during rollup

src/style.css
- add importance to override styling of components
- fixes checkboxes having issues with gcweb template repo
no related tickets
no screenshots
=> [Fix] Add importance to override styling

src/components/Details/Details.tsx, src/components/Details/stories/Details.intro.stories.mdx
- Extended to correct types to solve Typescript issue of defining props
No related tickets
=> [Fix] Extended input type for correct props for details

src/components/Form/FormCheck.tsx, src/components/Form/FormControl.tsx
⭐ **Fixes:**
- Fixed proptype issues with ref from components
=> [Fix] Resolve Typescript errors

src/components/Jumbotron/Jumbotron.test.tsx, src/components/Jumbotron/Jumbotron.tsx, src/components/Jumbotron/index.ts, src/components/Jumbotron/stories/Jumbotron.fluid.stories.mdx, src/components/Jumbotron/stories/Jumbotron.intro.stories.mdx, src/components/index.ts
- Implemented Jumbotron Component
- Added testing for Jumbotron Component
=> [New] Implement Jumbotron Component

package-lock.json, package.json, rollup.config.js
- resolve issue with rollup failing on build
no visual changes
=> [Fix] resolve rollup/build failure

.github/workflows/ci-tests.yaml
- add a build step to CI workflow to catch build failures
=> [New] add a build step to CI workflow

src/components/Form/FormCheck.tsx, src/components/Form/FormControl.tsx, src/components/Form/FormGroup.tsx, src/components/Form/FormGroupContext.ts, src/components/Form/FormLabel.tsx, src/components/Form/FormSelect.tsx, src/components/Form/FormText.tsx, src/components/Form/stories/Form.intro.stories.mdx
- pass 'isInvalid' and 'isRequired' from `<Form.Group>` to `<Form.Label>` and various form controls
- add error className to form control if invalid
no related issue
=> [New] implement useContext in `FormGroup`

src/components/Form/FormCheck.tsx, src/components/Form/FormCheckGroup.tsx, src/components/Form/FormLabel.tsx, src/components/Form/index.ts, src/components/Form/stories/Form.check.group.stories.mdx, src/components/Form/stories/Form.check.stories.mdx, src/components/Form/stories/Form.label.stories.mdx, src/style.css
- Implement form check/radio group component
- improve a11y of checkboxes and radios
=> [New] Implement form check/radio group component

README.md
=> [Fix] Update link to npm

src/components/Form/stories/Form.check.stories.mdx
- resolve the error that prevented `form.check` stories from loading
resolves #79 
=> [Fix] Resolve error in 'form.check' story

src/components/Form/Form.test.tsx, src/components/Form/FormCheck.tsx, src/components/Form/FormCheckGroup.tsx
- Added tests for forms
- Reached 100% code coverage
resolves issue #49
=> Implement form tests

src/components/Alert/stories/Alert.intro.stories.mdx, src/components/Jumbotron/stories/Jumbotron.intro.stories.mdx, src/components/ListGroup/ListGroup.tsx, src/components/ListGroup/stories/ListGroup.active.stories.mdx, src/components/ListGroup/stories/ListGroup.intro.stories.mdx, src/components/ListGroup/stories/ListGroup.links.stories.mdx, src/components/ListGroup/stories/ListGroup.variants.stories.mdx
resolves issue #76 by giving the List group component its documentation.
=> List Group Documentation Fix

src/components/Button/Button.tsx, src/components/Button/stories/Button.disabled.stories.mdx
- Fixed as prop's interaction with storybook
=> [Fix] Updated Button stories

src/components/Table/Table.test.tsx, src/components/Table/TableBody.tsx, src/components/Table/index.ts, src/components/Table/stories/Table.intro.stories.mdx, src/components/Table/stories/Table.styling.stories.mdx, src/components/Table/stories/Table.variants.stories.mdx
- add Table.Body component
- Fix incorrect source code rendering for table documentation
- polish table documentation
=> [Fix] fix documentation for Table component

src/components/Form/Form.test.tsx, src/components/Form/FormControl.tsx, src/components/Form/stories/Form.control.stories.mdx
- Added min and max property to Form.Control
=> [Fix] Added min and max prop to 'Form.Control'

src/components/Form/Form.test.tsx, src/components/Form/FormCheck.tsx
- display custom required message for form check
- update tests
=> [Fix] display custom required message

src/components/Form/FormControl.tsx
- allow min and max to be string for date picker
=> [Fix] update type for min and max props for 'Form.Control'
